package routeros

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

/*
  {
    ".id": "*1",
    "afi": "ip",
    "areas": "49.2222",
    "areas-max": "",
    "comment": "",
    "disabled": "false",
    "in-filter-chain": "",
    "inactive": "false",
    "l1.lsp-max-age": "",
    "l1.lsp-max-size": "",
    "l1.lsp-refresh-interval": "",
    "l1.lsp-update-interval": "",
    "l1.originate-default": "always",
    "l1.out-filter-chain": "",
    "l1.out-filter-select": "",
    "l1.redistribute": "",
    "l2.lsp-max-age": "",
    "l2.lsp-max-size": "",
    "l2.lsp-refresh-interval": "",
    "l2.lsp-update-interval": "",
    "l2.originate-default": "always",
    "l2.out-filter-chain": "",
    "l2.out-filter-select": "",
    "l2.redistribute": "",
    "metric-type": "",
    "name": "isis-instance-1",
    "system-id": "90ab.cdef.0001",
    "vrf": "main"
  }
*/

// ResourceRoutingIsisInstance https://help.mikrotik.com/docs/spaces/ROS/pages/201523543/IS-IS
func ResourceRoutingIsisInstance() *schema.Resource {
	resSchema := map[string]*schema.Schema{
		MetaResourcePath: PropResourcePath("/routing/isis/instance"),
		MetaId:           PropId(Id),
		MetaTransformSet: PropTransformSet(
			"l1_lsp_max_age: l1.lsp-max-age",
			"l1_lsp_max_size: l1.lsp-max-size",
			"l1_lsp_refresh_interval: l1.lsp-refresh-interval",
			"l1_lsp_update_interval: l1.lsp-update-interval",
			"l1_originate_default: l1.originate-default",
			"l1_out_filter_chain: l1.out-filter-chain",
			"l1_out_filter_select: l1.out-filter-select",
			"l1_redistribute: l1.redistribute",
			"l2_lsp_max_age: l2.lsp-max-age",
			"l2_lsp_max_size: l2.lsp-max-size",
			"l2_lsp_refresh_interval: l2.lsp-refresh-interval",
			"l2_lsp_update_interval: l2.lsp-update-interval",
			"l2_originate_default: l2.originate-default",
			"l2_out_filter_chain: l2.out-filter-chain",
			"l2_out_filter_select: l2.out-filter-select",
			"l2_redistribute: l2.redistribute",
		),

		"afi": {
			Type:         schema.TypeString,
			Optional:     true,
			Description:  "The address family this instance operates on.",
			ValidateFunc: validation.StringInSlice([]string{"ip", "ipv6"}, false),
		},
		"areas": {
			Type:     schema.TypeSet,
			Optional: true,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "The area addresses of this IS-IS instance, that is the area part of the NET, for example " +
				"`49.0001`. An instance may hold several area addresses during a reconfiguration.",
		},
		"areas_max": {
			Type:             schema.TypeInt,
			Optional:         true,
			Description:      "The maximum number of area addresses the instance accepts.",
			DiffSuppressFunc: AlwaysPresentNotUserProvided,
		},
		KeyComment:  PropCommentRw,
		KeyDisabled: PropDisabledRw,
		"in_filter_chain": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "Name of the routing filter chain that is applied to the routes received by this instance.",
		},
		KeyInactive: PropInactiveRo,
		"l1_lsp_max_age": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "The lifetime advertised in the level 1 link state PDUs. A neighbor purges an LSP that " +
				"has not been refreshed within this time.",
			ValidateFunc:     ValidationTime,
			DiffSuppressFunc: TimeEqual,
		},
		"l1_lsp_max_size": {
			Type:             schema.TypeInt,
			Optional:         true,
			Description:      "The maximum size in bytes of a level 1 link state PDU generated by this instance.",
			DiffSuppressFunc: AlwaysPresentNotUserProvided,
		},
		"l1_lsp_refresh_interval": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "The interval at which the own level 1 link state PDUs are regenerated so that they never " +
				"reach their maximum age.",
			ValidateFunc:     ValidationTime,
			DiffSuppressFunc: TimeEqual,
		},
		"l1_lsp_update_interval": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "The minimum interval between two consecutive regenerations of the own level 1 link state " +
				"PDUs after a topology change.",
			ValidateFunc:     ValidationTime,
			DiffSuppressFunc: TimeEqual,
		},
		"l1_originate_default": {
			Type:         schema.TypeString,
			Optional:     true,
			Description:  "Controls the origination of the default route into the level 1 database.",
			ValidateFunc: validation.StringInSlice([]string{"always", "if-installed", "never"}, false),
		},
		"l1_out_filter_chain": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "Name of the routing filter chain applied to the routes advertised into the level 1 " +
				"database.",
		},
		"l1_out_filter_select": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "Name of the `/routing/filter/select-rule` chain that decides which of the candidate " +
				"routes are advertised into the level 1 database.",
		},
		"l1_redistribute": {
			Type:     schema.TypeSet,
			Optional: true,
			Elem: &schema.Schema{
				Type: schema.TypeString,
				ValidateDiagFunc: ValidationMultiValInSlice([]string{"bgp", "bgp-mpls-vpn", "connected", "dhcp",
					"fantasy", "modem", "ospf", "rip", "slaac", "static", "vpn"}, false, false),
			},
			Description: "Enable the redistribution of the listed route types into the level 1 database.",
		},
		"l2_lsp_max_age": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "The lifetime advertised in the level 2 link state PDUs. A neighbor purges an LSP that " +
				"has not been refreshed within this time.",
			ValidateFunc:     ValidationTime,
			DiffSuppressFunc: TimeEqual,
		},
		"l2_lsp_max_size": {
			Type:             schema.TypeInt,
			Optional:         true,
			Description:      "The maximum size in bytes of a level 2 link state PDU generated by this instance.",
			DiffSuppressFunc: AlwaysPresentNotUserProvided,
		},
		"l2_lsp_refresh_interval": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "The interval at which the own level 2 link state PDUs are regenerated so that they never " +
				"reach their maximum age.",
			ValidateFunc:     ValidationTime,
			DiffSuppressFunc: TimeEqual,
		},
		"l2_lsp_update_interval": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "The minimum interval between two consecutive regenerations of the own level 2 link state " +
				"PDUs after a topology change.",
			ValidateFunc:     ValidationTime,
			DiffSuppressFunc: TimeEqual,
		},
		"l2_originate_default": {
			Type:         schema.TypeString,
			Optional:     true,
			Description:  "Controls the origination of the default route into the level 2 database.",
			ValidateFunc: validation.StringInSlice([]string{"always", "if-installed", "never"}, false),
		},
		"l2_out_filter_chain": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "Name of the routing filter chain applied to the routes advertised into the level 2 " +
				"database.",
		},
		"l2_out_filter_select": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "Name of the `/routing/filter/select-rule` chain that decides which of the candidate " +
				"routes are advertised into the level 2 database.",
		},
		"l2_redistribute": {
			Type:     schema.TypeSet,
			Optional: true,
			Elem: &schema.Schema{
				Type: schema.TypeString,
				ValidateDiagFunc: ValidationMultiValInSlice([]string{"bgp", "bgp-mpls-vpn", "connected", "dhcp",
					"fantasy", "modem", "ospf", "rip", "slaac", "static", "vpn"}, false, false),
			},
			Description: "Enable the redistribution of the listed route types into the level 2 database.",
		},
		"metric_type": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "The style of the metrics generated and accepted by this instance." +
				"\n  * old - the narrow metrics of the original IS-IS specification" +
				"\n  * wide - the wide metrics of RFC 5305" +
				"\n  * both - generate and accept both metric styles",
			ValidateFunc: validation.StringInSlice([]string{"both", "old", "wide"}, false),
		},
		KeyName: PropName("Name of the IS-IS instance, referenced by the interface templates."),
		"system_id": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "The six byte system identifier of this router, written as three groups of four " +
				"hexadecimal digits, for example `90ab.cdef.0001`. It has to be unique in the whole IS-IS domain.",
		},
		KeyVrf: PropVrfRw,
	}

	return &schema.Resource{
		CreateContext: DefaultCreate(resSchema),
		ReadContext:   DefaultRead(resSchema),
		UpdateContext: DefaultUpdate(resSchema),
		DeleteContext: DefaultDelete(resSchema),

		Importer: &schema.ResourceImporter{
			StateContext: ImportStateCustomContext(resSchema),
		},

		Schema: resSchema,
	}
}
