package routeros

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

/*
  {
    ".id": "*1",
    "comment": "",
    "count": "",
    "dealer-id": "",
    "disabled": "false",
    "dst-address": "",
    "gateway": "",
    "instance-id": "",
    "invalid": "false",
    "name": "",
    "offset": "",
    "prefix-length": "",
    "priv-offs": "",
    "priv-size": "",
    "scope": "",
    "seed": "",
    "target-scope": "",
    "use-hold": "false"
  }
*/

// ResourceRoutingFantasy A synthetic route generator. RouterOS uses the `fantasy` routes to load the routing
// table with artificial prefixes, and `fantasy` is one of the values accepted by the `redistribute` property of
// the routing protocols.
//
// This menu is undocumented; property value domains are unknown, so the value-carrying properties are
// plain strings passed to the device verbatim.
func ResourceRoutingFantasy() *schema.Resource {
	const verify = "VERIFY: the value domain of this property could not be established, the RouterOS console " +
		"offers no completions for it and the menu is undocumented. Supply the raw RouterOS value."

	resSchema := map[string]*schema.Schema{
		MetaResourcePath: PropResourcePath("/routing/fantasy"),
		MetaId:           PropId(Id),
		// The RouterOS property is called 'count', which is a reserved attribute name in Terraform.
		MetaTransformSet: PropTransformSet("route_count: count"),

		KeyComment: PropCommentRw,
		"route_count": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "The number of synthetic routes generated by this entry. Maps to the RouterOS `count` " +
				"property. " + verify,
		},
		"dealer_id": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "Identifier of the generator that hands out the synthetic routes. " + verify,
		},
		KeyDisabled: PropDisabledRw,
		"dst_address": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "The base destination prefix the generated routes start from. " + verify,
		},
		"gateway": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "The gateway assigned to the generated routes. " + verify,
		},
		"instance_id": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "Identifier of the generator instance. " + verify,
		},
		KeyInvalid: PropInvalidRo,
		KeyName:    PropName("Name of the synthetic route generator entry."),
		"offset": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "The offset applied to the generated destination prefixes. " + verify,
		},
		"prefix_length": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "The prefix length of the generated destination prefixes. " + verify,
		},
		"priv_offs": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "Offset of the private part of the generated route data. " + verify,
		},
		"priv_size": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "Size of the private part of the generated route data. " + verify,
		},
		"scope": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "The route scope assigned to the generated routes. " + verify,
		},
		"seed": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "The seed of the pseudo random generator that produces the routes. " + verify,
		},
		"target_scope": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "The target scope assigned to the generated routes. " + verify,
		},
		"use_hold": {
			Type:     schema.TypeBool,
			Optional: true,
			Description: "Keep the generated routes in the hold state. " +
				"The console reports `yes` and `no` as the accepted values.",
			DiffSuppressFunc: AlwaysPresentNotUserProvided,
		},
	}

	return &schema.Resource{
		CreateContext: DefaultCreate(resSchema),
		ReadContext:   DefaultRead(resSchema),
		UpdateContext: DefaultUpdate(resSchema),
		DeleteContext: DefaultDelete(resSchema),

		Importer: &schema.ResourceImporter{
			StateContext: ImportStateCustomContext(resSchema),
		},

		Schema: resSchema,
	}
}
