package routeros

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

/*
	The menu was empty on the RouterOS 7.23, so no value sample is available.
	`expires` is ForceNew: MikroTik documents that it cannot be changed once the user exists, so a
	change recreates the user (regenerating its WireGuard keys).
*/

// https://help.mikrotik.com/docs/spaces/ROS/pages/197984280/Back+To+Home
func ResourceIpCloudBackToHomeUser() *schema.Resource {
	resSchema := map[string]*schema.Schema{
		MetaResourcePath: PropResourcePath("/ip/cloud/back-to-home-user"),
		MetaId:           PropId(Id),

		"allow_lan": {
			Type:     schema.TypeBool,
			Optional: true,
			Description: "Allows the user to reach the local network behind the router. When it is disabled the user " +
				"is added to a firewall address list that only permits internet access.",
			DiffSuppressFunc: AlwaysPresentNotUserProvided,
		},
		KeyComment:  PropCommentRw,
		KeyDisabled: PropDisabledRw,
		"expires": {
			Type:     schema.TypeString,
			Optional: true,
			ForceNew: true,
			Description: "Expiration time and date of the user, `never` or an ISO 8601 `YYYY-MM-DD HH:MM:SS` value. " +
				"MikroTik documents that it cannot be changed once the user has been created, so the resource is " +
				"recreated when this attribute changes.",
			DiffSuppressFunc: AlwaysPresentNotUserProvided,
		},
		"file_access": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "Level of access the user gets to the directory given by `file_access_path`." +
				"\n  * disabled - no file access at all." +
				"\n  * read-only - the user may browse and download." +
				"\n  * full - the user may also upload and delete.",
			ValidateFunc:     validation.StringInSlice([]string{"disabled", "full", "read-only"}, false),
			DiffSuppressFunc: AlwaysPresentNotUserProvided,
		},
		"file_access_path": {
			Type:     schema.TypeString,
			Optional: true,
			Description: "Directory on the router the user is allowed to browse. Using the router root (`/`) is not " +
				"recommended: a user with full access to it can delete system files or upload malicious `.npk` packages.",
			DiffSuppressFunc: AlwaysPresentNotUserProvided,
		},
		KeyName: PropName("Informative name of the Back To Home user."),
		"private_key": {
			Type:      schema.TypeString,
			Optional:  true,
			Computed:  true,
			Sensitive: true,
			Description: "WireGuard private key of the user. If it is not set manually, it is generated by the " +
				"system.",
		},
		"public_key": {
			Type:     schema.TypeString,
			Optional: true,
			Computed: true,
			Description: "WireGuard public key of the user. If it is not set manually, it is generated by the " +
				"system.",
		},
	}

	return &schema.Resource{
		CreateContext: DefaultCreate(resSchema),
		ReadContext:   DefaultRead(resSchema),
		UpdateContext: DefaultUpdate(resSchema),
		DeleteContext: DefaultDelete(resSchema),

		Importer: &schema.ResourceImporter{
			StateContext: ImportStateCustomContext(resSchema),
		},

		Schema: resSchema,
	}
}
